package com.glyphmark.intellij

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Asserts this lexer against the same fixtures the TypeScript one is pinned to.
 *
 * `libs/core/test/golden/<fixture>/golden.tokens.json` is generated by
 * `libs/core/test/golden/tokens.test.ts` and checked in. Both suites read it, so
 * either implementation drifting turns a build red immediately — which is the
 * only thing keeping two hand-written lexers in step.
 *
 * The fixtures carry no payload text on purpose: a kind and integers only. Two
 * languages cannot disagree about where column 6 is, but they certainly can
 * about what trimming a string means.
 */
class GlyphLexerGoldenTest {

    private val goldenDir: File by lazy {
        // Gradle runs tests from the plugin's project directory.
        val dir = File("../../libs/core/test/golden").canonicalFile
        assertTrue(dir.isDirectory, "golden fixtures not found at $dir")
        dir
    }

    private fun fixtures(): List<File> =
        goldenDir.listFiles()!!
            .filter { it.isDirectory && File(it, "golden.tokens.json").isFile }
            .sortedBy { it.name }

    @Test
    fun `every fixture has a golden to compare against`() {
        // Guards the harness itself: a wrong path would otherwise make this
        // whole class pass by iterating over nothing.
        assertTrue(fixtures().size >= 20, "expected the full corpus, found ${fixtures().size}")
    }

    @Test
    fun `matches the TypeScript token stream`() {
        val failures = mutableListOf<String>()

        for (fixture in fixtures()) {
            val input = File(fixture, "input.glyph").readText()
            val expected = parseGolden(File(fixture, "golden.tokens.json").readText())
            val actual = GlyphLexer.tokenize(input).map(::describe)

            if (expected.size != actual.size) {
                failures += "${fixture.name}: ${actual.size} tokens, expected ${expected.size}"
                continue
            }
            for (i in expected.indices) {
                if (expected[i] != actual[i]) {
                    failures += "${fixture.name} token $i:\n  expected ${expected[i]}\n  actual   ${actual[i]}"
                }
            }
        }

        assertEquals(emptyList(), failures, failures.joinToString("\n"))
    }

    @Test
    fun `token stream tiles the source`() {
        // The contract IntelliJ's Lexer requires, asserted as a property over
        // the corpus rather than case by case. The TypeScript suite asserts the
        // same thing, so a port that classifies correctly but leaves a hole in
        // its coverage still fails.
        for (fixture in fixtures()) {
            val input = File(fixture, "input.glyph").readText()
            val tokens = GlyphLexer.tokenize(input)

            assertEquals(
                input.split("\n").size,
                tokens.size,
                "${fixture.name}: one token per line",
            )

            var cursor = 0
            for (tok in tokens) {
                assertEquals(cursor, tok.startOffset, "${fixture.name} line ${tok.line}: gap or overlap")
                // +1 for the newline between lines; the last line has none.
                cursor = tok.endOffset + 1

                for (part in listOfNotNull(tok.keyword, tok.key, tok.marker, tok.content, tok.inner)) {
                    assertTrue(
                        part.start in 0..part.end && part.end <= tok.raw.length,
                        "${fixture.name} line ${tok.line}: part $part outside the line",
                    )
                }
            }
            assertEquals(input.length + 1, cursor, "${fixture.name}: stream stops short")
        }
    }

    /**
     * A token rendered the way the fixtures spell it, so the two sides compare
     * as plain strings and a mismatch reads clearly.
     */
    private fun describe(tok: GlyphToken): String = buildString {
        append(tok.kind.wireName)
        append(" line=").append(tok.line)
        append(" span=[").append(tok.startOffset).append(',').append(tok.endOffset).append(']')
        if (tok.level != 0) append(" level=").append(tok.level)
        appendPart("keyword", tok.keyword)
        appendPart("key", tok.key)
        appendPart("marker", tok.marker)
        appendPart("content", tok.content)
        appendPart("inner", tok.inner)
        if (tok.inline.isNotEmpty()) {
            append(" inline=")
            append(
                tok.inline.joinToString(",", "[", "]") {
                    "[\"${it.kind.wireName}\",${it.start},${it.end},${it.contentStart},${it.contentEnd}]"
                },
            )
        }
    }

    private fun StringBuilder.appendPart(name: String, part: Part?) {
        if (part == null) return
        append(' ').append(name).append("=[").append(part.start).append(',').append(part.end).append(']')
    }

    /**
     * Read the fixture into the same rendering.
     *
     * Hand-rolled rather than pulled from a JSON library: the plugin has no
     * runtime JSON dependency and the format here is one flat object per line by
     * construction, so a full parser would be more moving parts than the thing
     * it parses.
     */
    private fun parseGolden(text: String): List<String> =
        text.lineSequence()
            .map { it.trim().removeSuffix(",") }
            .filter { it.startsWith("{") }
            .map { line ->
                val fields = FIELD_RE.findAll(line).associate { m ->
                    m.groupValues[1] to m.groupValues[2].trim()
                }
                buildString {
                    append(fields.getValue("kind").trim('"'))
                    append(" line=").append(fields.getValue("line"))
                    append(" span=").append(fields.getValue("span"))
                    fields["level"]?.let { append(" level=").append(it) }
                    for (name in listOf("keyword", "key", "marker", "content", "inner")) {
                        fields[name]?.let { append(' ').append(name).append('=').append(it) }
                    }
                    // `inline` nests arrays, which the flat field regex cannot
                    // reach, and it is always written last — so it is taken
                    // from the line directly.
                    INLINE_RE.find(line)?.let {
                        append(" inline=").append(it.groupValues[1])
                    }
                }
            }
            .toList()

    private companion object {
        // `"name":value` where value is a string, a number, or a [a,b] pair.
        val FIELD_RE = Regex("\"(\\w+)\":(\"[^\"]*\"|\\[[^]]*]|[^,}]+)")

        // `"inline":[[...],[...]]` through to the end of the object.
        val INLINE_RE = Regex("\"inline\":(\\[.*])}$")
    }
}
